bda/urls.py
from django.conf.urls import url

from bda import views
from bda.views import SpectacleListView
from gestioncof.decorators import buro_required

urlpatterns = [
    url(
        r"^inscription/(?P<tirage_id>\d+)$",
        views.inscription,
        name="bda-tirage-inscription",
    ),
    url(r"^places/(?P<tirage_id>\d+)$", views.places, name="bda-places-attribuees"),
    url(r"^etat-places/(?P<tirage_id>\d+)$", views.etat_places, name="bda-etat-places"),
    url(r"^tirage/(?P<tirage_id>\d+)$", views.tirage, name="bda-tirage"),
    url(
        r"^spectacles/(?P<tirage_id>\d+)$",
        buro_required(SpectacleListView.as_view()),
        name="bda-liste-spectacles",
    ),
    url(
        r"^spectacles/(?P<tirage_id>\d+)/(?P<spectacle_id>\d+)$",
        views.spectacle,
        name="bda-spectacle",
    ),
    url(
        r"^spectacles/unpaid/(?P<tirage_id>\d+)$",
        views.UnpaidParticipants.as_view(),
        name="bda-unpaid",
    ),
    url(
        r"^spectacles/autocomplete$",
        views.spectacle_autocomplete,
        name="bda-spectacle-autocomplete",
    ),
    url(
        r"^participants/autocomplete$",
        views.participant_autocomplete,
        name="bda-participant-autocomplete",
    ),
    # Urls BdA-Revente
    url(
        r"^revente/(?P<tirage_id>\d+)/manage$",
        views.revente_manage,
        name="bda-revente-manage",
    ),
    url(
        r"^revente/(?P<tirage_id>\d+)/subscribe$",
        views.revente_subscribe,
        name="bda-revente-subscribe",
    ),
    url(
        r"^revente/(?P<tirage_id>\d+)/tirages$",
        views.revente_tirages,
        name="bda-revente-tirages",
    ),
    url(
        r"^revente/(?P<spectacle_id>\d+)/buy$",
        views.revente_buy,
        name="bda-revente-buy",
    ),
    url(
        r"^revente/(?P<revente_id>\d+)/confirm$",
        views.revente_confirm,
        name="bda-revente-confirm",
    ),
    url(
        r"^revente/(?P<tirage_id>\d+)/shotgun$",
        views.revente_shotgun,
        name="bda-revente-shotgun",
    ),
    url(r"^mails-rappel/(?P<spectacle_id>\d+)$", views.send_rappel, name="bda-rappels"),
    url(r"^catalogue/(?P<request_type>[a-z]+)$", views.catalogue, name="bda-catalogue"),
]

petitscours/urls.py
from django.urls import path

from gestioncof.decorators import buro_required
from petitscours import views
from petitscours.views import DemandeDetailView, DemandeListView

urlpatterns = [
    path("inscription", views.inscription, name="petits-cours-inscription"),
    path("demande", views.demande, name="petits-cours-demande"),
    path(
        "demande-raw",
        views.demande,
        kwargs={"raw": True},
        name="petits-cours-demande-raw",
    ),
    path(
        "demandes",
        buro_required(DemandeListView.as_view()),
        name="petits-cours-demandes-list",
    ),
    path(
        "demandes/<int:pk>",
        buro_required(DemandeDetailView.as_view()),
        name="petits-cours-demande-details",
    ),
    path(
        "demandes/<int:demande_id>/traitement",
        views.traitement,
        name="petits-cours-demande-traitement",
    ),
    path(
        "demandes/<int:demande_id>/retraitement",
        views.traitement,
        kwargs={"redo": True},
        name="petits-cours-demande-retraitement",
    ),
]

petitscours/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Min
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _

from shared.utils import choices_length

LEVELS_CHOICES = (
    ("college", _("Collège")),
    ("lycee", _("Lycée")),
    ("prepa1styear", _("Prépa 1ère année / L1")),
    ("prepa2ndyear", _("Prépa 2ème année / L2")),
    ("licence3", _("Licence 3")),
    ("master1", _("Master (1ère ou 2ème année)")),
    ("other", _("Autre (préciser dans les commentaires)")),
)


class PetitCoursSubject(models.Model):
    name = models.CharField(_("Matière"), max_length=30)
    users = models.ManyToManyField(
        User, related_name="petits_cours_matieres", through="PetitCoursAbility"
    )

    class Meta:
        app_label = "gestioncof"
        verbose_name = "Matière de petits cours"
        verbose_name_plural = "Matières des petits cours"

    def __str__(self):
        return self.name


class PetitCoursAbility(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    matiere = models.ForeignKey(
        PetitCoursSubject, on_delete=models.CASCADE, verbose_name=_("Matière")
    )
    niveau = models.CharField(
        _("Niveau"), choices=LEVELS_CHOICES, max_length=choices_length(LEVELS_CHOICES)
    )
    agrege = models.BooleanField(_("Agrégé"), default=False)

    class Meta:
        app_label = "gestioncof"
        verbose_name = "Compétence petits cours"
        verbose_name_plural = "Compétences des petits cours"

    def __str__(self):
        return "{:s} - {!s} - {:s}".format(
            self.user.username, self.matiere, self.niveau
        )

    @cached_property
    def counter(self) -> int:
        """Le compteur d'attribution associé au professeur pour cette matière."""

        return PetitCoursAttributionCounter.get_uptodate(self.user, self.matiere).count


class PetitCoursDemande(models.Model):
    name = models.CharField(_("Nom/prénom"), max_length=200)
    email = models.CharField(_("Adresse email"), max_length=300)
    phone = models.CharField(_("Téléphone (facultatif)"), max_length=20, blank=True)
    quand = models.CharField(
        _("Quand ?"),
        help_text=_(
            "Indiquez ici la période désirée pour les petits"
            " cours (vacances scolaires, semaine, week-end)."
        ),
        max_length=300,
        blank=True,
    )
    freq = models.CharField(
        _("Fréquence"),
        help_text=_(
            "Indiquez ici la fréquence envisagée "
            "(hebdomadaire, 2 fois par semaine, ...)"
        ),
        max_length=300,
        blank=True,
    )
    lieu = models.CharField(
        _("Lieu (si préférence)"),
        help_text=_("Si vous avez avez une préférence sur le lieu."),
        max_length=300,
        blank=True,
    )

    matieres = models.ManyToManyField(
        PetitCoursSubject, verbose_name=_("Matières"), related_name="demandes"
    )
    agrege_requis = models.BooleanField(_("Agrégé requis"), default=False)
    niveau = models.CharField(
        _("Niveau"),
        default="",
        choices=LEVELS_CHOICES,
        max_length=choices_length(LEVELS_CHOICES),
    )

    remarques = models.TextField(_("Remarques et précisions"), blank=True)

    traitee = models.BooleanField(_("Traitée"), default=False)
    traitee_par = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True
    )
    processed = models.DateTimeField(_("Date de traitement"), blank=True, null=True)
    created = models.DateTimeField(_("Date de création"), auto_now_add=True)

    def get_candidates(self, redo=False):
        """
        Donne la liste des profs disponibles pour chaque matière de la demande.
        - On ne donne que les agrégés si c'est demandé
        - Si ``redo`` vaut ``True``, cela signifie qu'on retraite la demande et
          il ne faut pas proposer à nouveau des noms qui ont déjà été proposés
        """
        for matiere in self.matieres.all():
            candidates = PetitCoursAbility.objects.filter(
                matiere=matiere,
                niveau=self.niveau,
                user__profile__is_cof=True,
                user__profile__petits_cours_accept=True,
            )
            if self.agrege_requis:
                candidates = candidates.filter(agrege=True)
            if redo:
                attrs = self.petitcoursattribution_set.filter(matiere=matiere)
                already_proposed = [attr.user for attr in attrs]
                candidates = candidates.exclude(user__in=already_proposed)
            candidates = candidates.order_by("?").select_related().all()
            yield (matiere, candidates)

    def get_proposals(self, *, max_candidates: int = None, redo: bool = False):
        """Calcule une proposition de profs pour la demande.

        Args:
            max_candidates (optionnel; défaut: `None`):  Le nombre maximum de
                candidats à proposer par demande.  Si `None` ou non spécifié,
                il n'y a pas de limite.

            redo (optionel; défaut: `False`):  Détermine si on re-calcule les
                propositions pour la demande (les professeurs à qui on a déjà
                proposé cette demande sont exclus).

        Returns:
            proposals:  Le dictionnaire qui associe à chaque matière la liste
                des professeurs proposés.  Les matières pour lesquelles aucun
                professeur n'est disponible ne sont pas présentes dans
                `proposals`.
            unsatisfied:  La liste des matières pour lesquelles aucun
                professeur n'est disponible.
        """

        proposals = {}
        unsatisfied = []
        for matiere, candidates in self.get_candidates(redo=redo):
            if not candidates:
                unsatisfied.append(matiere)
            else:
                proposals[matiere] = matiere_proposals = []

                candidates = sorted(candidates, key=lambda c: c.counter)
                candidates = candidates[:max_candidates]
                for candidate in candidates[:max_candidates]:
                    matiere_proposals.append(candidate.user)

        return proposals, unsatisfied

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("petits-cours-demande-details", kwargs={"pk": str(self.id)})

    class Meta:
        app_label = "gestioncof"
        verbose_name = "Demande de petits cours"
        verbose_name_plural = "Demandes de petits cours"

    def __str__(self):
        return "Demande {:d} du {:s}".format(self.id, self.created.strftime("%d %b %Y"))


class PetitCoursAttribution(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    demande = models.ForeignKey(
        PetitCoursDemande, on_delete=models.CASCADE, verbose_name=_("Demande")
    )
    matiere = models.ForeignKey(
        PetitCoursSubject, on_delete=models.CASCADE, verbose_name=_("Matière")
    )
    date = models.DateTimeField(_("Date d'attribution"), auto_now_add=True)
    rank = models.IntegerField("Rang dans l'email")
    selected = models.BooleanField(_("Sélectionné par le demandeur"), default=False)

    class Meta:
        app_label = "gestioncof"
        verbose_name = "Attribution de petits cours"
        verbose_name_plural = "Attributions de petits cours"

    def __str__(self):
        return "Attribution de la demande {:d} à {:s} pour {!s}".format(
            self.demande.id, self.user.username, self.matiere
        )


class PetitCoursAttributionCounter(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    matiere = models.ForeignKey(
        PetitCoursSubject, on_delete=models.CASCADE, verbose_name=_("Matiere")
    )
    count = models.IntegerField("Nombre d'envois", default=0)

    @classmethod
    def get_uptodate(cls, user, matiere):
        """
        Donne le compteur de l'utilisateur pour cette matière. Si le compteur
        n'existe pas encore, il est initialisé avec le minimum des valeurs des
        compteurs de tout le monde.
        """
        counter, created = cls.objects.get_or_create(user=user, matiere=matiere)
        if created:
            mincount = (
                cls.objects.filter(matiere=matiere)
                .exclude(user=user)
                .aggregate(Min("count"))["count__min"]
            )
            counter.count = mincount or 0
            counter.save()
        return counter

    class Meta:
        app_label = "gestioncof"
        verbose_name = "Compteur d'attribution de petits cours"
        verbose_name_plural = "Compteurs d'attributions de petits cours"

    def __str__(self):
        return "{:d} demandes envoyées à {:s} pour {!s}".format(
            self.count, self.user.username, self.matiere
        )

petitscours/forms.py
from captcha.fields import ReCaptchaField
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.forms.models import BaseInlineFormSet, inlineformset_factory

from petitscours.models import PetitCoursAbility, PetitCoursDemande


class BaseMatieresFormSet(BaseInlineFormSet):
    def clean(self):
        super().clean()
        if any(self.errors):
            # Don't bother validating the formset unless each form is
            # valid on its own
            return
        matieres = []
        for i in range(0, self.total_form_count()):
            form = self.forms[i]
            if not form.cleaned_data:
                continue
            matiere = form.cleaned_data["matiere"]
            niveau = form.cleaned_data["niveau"]
            delete = form.cleaned_data["DELETE"]
            if not delete and (matiere, niveau) in matieres:
                raise forms.ValidationError(
                    "Vous ne pouvez pas vous inscrire deux fois pour la "
                    "même matiere avec le même niveau."
                )
            matieres.append((matiere, niveau))


class DemandeForm(ModelForm):
    captcha = ReCaptchaField(attrs={"theme": "clean", "lang": "fr"})

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["matieres"].help_text = ""

    class Meta:
        model = PetitCoursDemande
        fields = (
            "name",
            "email",
            "phone",
            "quand",
            "freq",
            "lieu",
            "matieres",
            "agrege_requis",
            "niveau",
            "remarques",
        )
        widgets = {"matieres": forms.CheckboxSelectMultiple}


MatieresFormSet = inlineformset_factory(
    User,
    PetitCoursAbility,
    fields=("matiere", "niveau", "agrege"),
    formset=BaseMatieresFormSet,
)

petitscours/templates/petitscours/base_title.html
{% extends "base_title.html" %}

petitscours/templates/petitscours/demande.html
{% extends "base_title.html" %}

{% block realcontent %}
                <h2>Demande de petits cours</h2>
                {% if success %}
                <p class="success">Votre demande a été enregistrée avec succès !</p>
                {% else %}
                <form id="demandecours" method="post" action="{% url "petits-cours-demande" %}">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" class="btn-submit" value="Enregistrer" />
                </form>
                {% endif %}
{% endblock %}

petitscours/templates/petitscours/demande_detail.html
{% extends "petitscours/base_title.html" %}
{% load staticfiles %}

{% block page_size %}col-sm-8{% endblock %}

{% block realcontent %}
    <h2>
        Demande de petits cours&nbsp;
        <a style="float: right" href="{% url 'admin:gestioncof_petitcoursdemande_change' demande.id %}">
            <span class="glyphicon glyphicon-edit"></span> Modifier
        </a>
    </h2>
    {% include "petitscours/details_demande_infos.html" %}
    <hr />
    <table class="table table-striped">
        <tr><td><strong>Traitée</strong></td><td> <img src="{% if demande.traitee %}{% static "gestioncof/vendor/font-awesome/images/yes.png" %}{% else %}{% static "gestioncof/vendor/font-awesome/images/no.png" %}{% endif %}" /></td></tr>
        {% if demande.traitee %}
        <tr><td><strong>Traitée par</strong></td><td> {{ demande.traitee_par }}</td></tr>
        <tr><td><strong>Traitée le</strong></td><td> {{ demande.processed }}</td></tr>
        <tr><td>
            <strong>Attributions</strong></td><td>
            <ul>
            {% for attrib in attributions %}
                <li>{{ attrib.user.get_full_name }} pour {{ attrib.matiere }}, {{ attrib.date|date:"d E Y" }}</li>
            {% endfor %}
            </ul>
        </td>
        </tr>
        {% endif %}
    </table>
    <div>
        <a href="{% url 'petits-cours-demandes-list' %}">Retour à la liste des demandes</a>

        {% if demande.traitee %}
        <form
            style="float: right"
            action="{% url "petits-cours-demande-retraitement" demande.id %}"
        >
            <input class="btn btn-primary" type="submit" value="Retraiter">
        </form>
        {% else %}
        <form
            style="float: right"
            action="{% url "petits-cours-demande-traitement" demande.id %}"
        >
            <input class="btn btn-primary" type="submit" value="Traiter">
        </form>
        {% endif %}
    </div>
{% endblock %}

petitscours/templates/petitscours/demande_list.html
{% extends "petitscours/base_title.html" %}
{% load staticfiles %}

{% block realcontent %}
    <h2>Demandes de petits cours</h2>
{% if object_list %}
    <table class="table table-stripped">
        <thead>
            <th>Nom</th>
            <th>Matières</th>
            <th>Date</th>
            <th>Traitée</th>
            <th>par</th>
            <th></th>
        </thead>
        <tbody>
        {% for demande in object_list %}
            <tr>
                <td>{{ demande.name }}</td>
                <td>{% for matiere in demande.matieres.all %}{% if forloop.counter0 > 0 %}, {% endif %}{{ matiere }}{% endfor %}</td>
                <td>{{ demande.created|date:"d E Y" }}</td>
		<td style="text-align: center;"><img src="{% if demande.traitee %}{% static "gestioncof/vendor/font-awesome/images/yes.png" %}{% else %}{% static "gestioncof/vendor/font-awesome/images/no.png" %}{% endif %}" /></td>
                <td>{% if demande.traitee_par %}{{ demande.traitee_par.username }}{% else %}<span class="glyphicon glyphicon-ban-circle"></span>{% endif %}</td>
                <td><a href="{% url "petits-cours-demande-details" demande.id %}" class="see_detail">Détails</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url "petits-cours-demandes-list" %}?page={{ page_obj.previous_page_number }}">&lt;</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url "petits-cours-demandes-list" %}?page={{ page_obj.next_page_number }}">&gt;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% else %}
    <p>Aucune demande :(</p>
{% endif %}
{% endblock %}

petitscours/templates/petitscours/demande_raw.html
{% extends "base.html" %}

{% load bootstrap %}

{% block content %}
<div class="petitcours-raw">
{% if success %}
<p class="success">Votre demande a été enregistrée avec succès !</p>
{% else %}
<form id="demandecours" method="post" action="{% url "petits-cours-demande-raw" %}">
    {% csrf_token %}
    <table>
    {{ form | bootstrap }}
    </table>
    <input type="submit" class="btn-submit" value="Enregistrer" />
</form>
{% endif %}
</div>
{% endblock %}

petitscours/templates/petitscours/details_demande_infos.html
{% load staticfiles %}
    <table class="table table-striped">
        <tr class="danger"><td><strong>Date</strong></td><td> {{ demande.created }}</td></tr>
        <tr class="warning"><td><strong>Nom/prénom</strong></td><td> {{ demande.name }}</td></tr>
        <tr><td><strong>Email</strong></td><td> {{ demande.email }}</td></tr>
        <tr><td><strong>Téléphone</strong></td><td> {{ demande.phone }}</td></tr>
        <tr><td><strong>Lieu</strong></td><td> {{ demande.lieu }}</td></tr>
        <tr><td><strong>Quand</strong></td><td> {{ demande.quand }}</td></tr>
        <tr><td><strong>Fréquence</strong></td><td> {{ demande.freq }}</td></tr>
        <tr><td><strong>Matières</strong></td><td> {% for matiere in demande.matieres.all %}{% if forloop.counter0 > 0 %}, {% endif %}{{ matiere }}{% endfor %}</td></tr>
        <tr><td><strong>Niveau souhaité</strong></td><td> {{ demande.get_niveau_display }}</td></tr>
	<tr><td><strong>Agrégé requis</strong></td><td> <img src="{% if demande.agrege_requis %}{% static "gestioncof/vendor/font-awesome/images/yes.png" %}{% else %}{% static "gestioncof/vendor/font-awesome/images/no.png" %}{% endif %}" /></td></tr>
        <tr><td><strong>Remarques</strong></td><td> {{ demande.remarques }}</td></tr>
    </table>

petitscours/templates/petitscours/inscription.html
{% extends "base_title.html" %}
{% load staticfiles %}

{% block extra_head %}
<script src="{% static 'vendor/jquery/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'gestioncof/vendor/jquery.ui.touch-punch.min.js' %}" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" href="{% static 'vendor/jquery/jquery-ui.min.css' %}" />

{% endblock %}

{% block realcontent %}
<script type="text/javascript">
var django = {
    "jQuery": jQuery.noConflict(true)
};

(function($) {
    cloneMore = function(selector, type) {
        var newElement = $(selector).clone(true);
        var total = $('#id_' + type + '-TOTAL_FORMS').val();
        newElement.find(':input').each(function() {
            var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
            var id = 'id_' + name;
            $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
        });
        total++;
        $('#id_' + type + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
    }
    deleteButtonHandler = function(elem) {
        elem.bind("click", function() {
            var deleteInput = $(this).prev(),
                form = $(this).parents(".dynamic-form").first();
            // callback
            // toggle options.predeleteCssClass and toggle checkbox
            if (form.hasClass("has_original")) {
                form.toggleClass("predelete");
                if (deleteInput.attr("checked")) {
                    deleteInput.attr("checked", false);
                } else {
                    deleteInput.attr("checked", true);
                }
            }
            // callback
        });
    }; 
    $(document).ready(function($) {
        deleteButtonHandler($("table#bda_formset tbody.bda_formset_content").find("a.remove-btn"));
        $("table#bda_formset tbody.bda_formset_content").sortable({
            handle: "a.drag-handler",
            items: "tr",
            axis: "y",
            appendTo: 'body',
            forceHelperSize: true,
            placeholder: 'ui-sortable-placeholder',
            forcePlaceholderSize: true,
            containment: 'form#bda_form',
            tolerance: 'pointer',
            start: function(evt, ui) {
                var template = "",
                    len = ui.item.children("td").length;
                for (var i = 0; i < len; i++) {
                    template += "<td style='height:" + (ui.item.outerHeight() + 12 ) + "px' class='placeholder-cell'>&nbsp;</td>"
                }
                template += "";
                ui.placeholder.html(template);
            },
            stop: function(evt, ui) {
                // Toggle div.table twice to remove webkits border-spacing bug
                $("table#bda_formset").toggle().toggle();
            },
        });
        $("#bda_form").bind("submit", function(){
            var sortable_field_name = "priority";
            var i = 1;
            $(".bda_formset_content").find("tr").each(function(){
                var fields = $(this).find("td :input[value]"),
                    select = $(this).find("td select");
                if (select.val() && fields.serialize()) {
                    $(this).find("input[name$='"+sortable_field_name+"']").val(i);
                    i++;
                }
            });
        });
        
    });
})(django.jQuery);
</script>

        <h2 class="no-bottom-margin">Inscription pour donner des cours particuliers</h2>
        {% if success %}
        <p class="success table-top">Votre inscription a été mise à jour avec succès !</p>
        {% endif %}
        <form class="form-horizontal  petit-cours_form" id="bda_form" method="post" action="{% url 'petits-cours-inscription' %}">
                {% csrf_token %}
                <div class="table-top" style="margin-left:0px; margin-right:0px; font-size: 1.25em; font-weight: bold; color: #DE826B;"><input type="checkbox" name="receive_proposals" {% if receive_proposals %}checked="checked"{% endif %} /> Recevoir des propositions de petits cours</div>
                {% include "petitscours/inscription_formset.html" %}
                <div class="inscription-bottom">
                    <input type="button" class="btn btn-default pull-right" value="Ajouter une autre matière" id="add_more" />
                    <script>
                        django.jQuery('#add_more').click(function() {
                            cloneMore('tbody.bda_formset_content tr:last-child', 'petitcoursability_set');
                        });
                    </script><br />
                    <div style="margin: 10px 0px;">
                    <span style="vertical-align: top; font-weight: bold;">Remarques:</span> <textarea name="remarques" style="width: 60%; height: 60px;">{{ remarques }}</textarea>
                    </div>
                    <input type="submit" class="btn btn-primary pull-right" value="Enregistrer" />
                    <p class="footnotes">
                        <sup>1</sup>: spécifiez les matières pour lesquelles vous êtes compétent<br />
                        <sup>2</sup>: spécifiez pour chaque matière le ou les niveaux pour lesquels vous souhaitez recevoir des demandes<br />
                        <sup>3</sup>: spécifiez si vous êtes titulaire de l'agrégation pour cette matière<br />
                        <sup>4</sup>: pour supprimer une ligne, cliquez sur la croix puis appuyer sur <tt>Enregistrer</tt><br />
                    </p>
                </div>
        </form>
{% endblock %}

petitscours/templates/petitscours/inscription_formset.html
{% load bootstrap %}
{{ formset.non_form_errors.as_ul }}
<table id="bda_formset" class="form table">
{{ formset.management_form }}
{% for form in formset.forms %}
  {% if forloop.first %}
  <thead><tr>
    {% for field in form.visible_fields %}
    <th class="bda-field-{{ field.name }}">
      {% if field.name != "DELETE" %}
    {{ field.label|safe|capfirst }}
      {% endif %}
      <sup>{{ forloop.counter }}</sup>
    </th>
    {% endfor %}
  </tr></thead>
   <tbody class="bda_formset_content">
  {% endif %}
    <tr class="{% cycle 'row1' 'row2' %} dynamic-form {% if form.instance.pk %}has_original{% endif %}">
    {% for field in form.visible_fields %}
      {% if field.name != "DELETE" and field.name != "priority" %}
      <td class="bda-field-{{ field.name }}">
      {% if forloop.first %}
        {{ form.non_field_errors }}
        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
      {% endif %}
        {{ field | bootstrap }}
      </td>
      {% endif %}
    {% endfor %}
    <td class="tools-cell"><div class="tools">
      <input type="checkbox" name="{{ form.DELETE.html_name }}" style="display: none;" />
      <a href="javascript://" class="glyphicon glyphicon-remove remove-btn" title="Supprimer"></a>
      </div>
      <div class="spacer"></div>
    </td>
    </tr>
{% endfor %}
  </tbody>
</table>

petitscours/templates/petitscours/traitement_demande_success.html
{% extends "petitscours/base_title.html" %}

{% block realcontent %}
    <h2>Traitement de la demande de petits cours {{ demande.id }}</h2>
    <div class="success" style="margin: 15px 0px; font-size: 1.4em;">Demande {{ demande.id }} de {{ demande.name }} {% if redo %}re{% endif %}traitée avec succès !</div>
    <a href="{% url "petits-cours-demandes-list" %}">Retour à la liste des demandes</a>
{% endblock %}