bda/urls.py
from django.conf.urls import url

from bda import views
from bda.views import SpectacleListView
from gestioncof.decorators import buro_required

urlpatterns = [
    url(
        r"^inscription/(?P<tirage_id>\d+)$",
        views.inscription,
        name="bda-tirage-inscription",
    ),
    url(r"^places/(?P<tirage_id>\d+)$", views.places, name="bda-places-attribuees"),
    url(r"^etat-places/(?P<tirage_id>\d+)$", views.etat_places, name="bda-etat-places"),
    url(r"^tirage/(?P<tirage_id>\d+)$", views.tirage, name="bda-tirage"),
    url(
        r"^spectacles/(?P<tirage_id>\d+)$",
        buro_required(SpectacleListView.as_view()),
        name="bda-liste-spectacles",
    ),
    url(
        r"^spectacles/(?P<tirage_id>\d+)/(?P<spectacle_id>\d+)$",
        views.spectacle,
        name="bda-spectacle",
    ),
    url(
        r"^spectacles/unpaid/(?P<tirage_id>\d+)$",
        views.UnpaidParticipants.as_view(),
        name="bda-unpaid",
    ),
    url(
        r"^spectacles/autocomplete$",
        views.spectacle_autocomplete,
        name="bda-spectacle-autocomplete",
    ),
    url(
        r"^participants/autocomplete$",
        views.participant_autocomplete,
        name="bda-participant-autocomplete",
    ),
    # Urls BdA-Revente
    url(
        r"^revente/(?P<tirage_id>\d+)/manage$",
        views.revente_manage,
        name="bda-revente-manage",
    ),
    url(
        r"^revente/(?P<tirage_id>\d+)/subscribe$",
        views.revente_subscribe,
        name="bda-revente-subscribe",
    ),
    url(
        r"^revente/(?P<tirage_id>\d+)/tirages$",
        views.revente_tirages,
        name="bda-revente-tirages",
    ),
    url(
        r"^revente/(?P<spectacle_id>\d+)/buy$",
        views.revente_buy,
        name="bda-revente-buy",
    ),
    url(
        r"^revente/(?P<revente_id>\d+)/confirm$",
        views.revente_confirm,
        name="bda-revente-confirm",
    ),
    url(
        r"^revente/(?P<tirage_id>\d+)/shotgun$",
        views.revente_shotgun,
        name="bda-revente-shotgun",
    ),
    url(r"^mails-rappel/(?P<spectacle_id>\d+)$", views.send_rappel, name="bda-rappels"),
    url(r"^catalogue/(?P<request_type>[a-z]+)$", views.catalogue, name="bda-catalogue"),
]

kfet/open/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("raw_open", views.raw_open, name="kfet.open.edit_raw_open"),
    path("force_close", views.force_close, name="kfet.open.edit_force_close"),
]

kfet/urls.py
from django.contrib.auth.decorators import permission_required
from django.urls import include, path, register_converter

from kfet import autocomplete, converters, views
from kfet.decorators import teamkfet_required

register_converter(converters.TrigrammeConverter, "trigramme")

urlpatterns = [
    path("login/generic", views.login_generic, name="kfet.login.generic"),
    path("history", views.history, name="kfet.history"),
    # -----
    # Account urls
    # -----
    # Account - General
    path("accounts/", views.account, name="kfet.account"),
    path(
        "accounts/is_validandfree",
        views.account_is_validandfree_ajax,
        name="kfet.account.is_validandfree.ajax",
    ),
    # Account - Create
    path("accounts/new", views.account_create, name="kfet.account.create"),
    path(
        "accounts/new/user/<username>",
        views.account_create_ajax,
        name="kfet.account.create.fromuser",
    ),
    path(
        "accounts/new/clipper/<slug:login_clipper>/<fullname>",
        views.account_create_ajax,
        name="kfet.account.create.fromclipper",
    ),
    path(
        "accounts/new/empty",
        views.account_create_ajax,
        name="kfet.account.create.empty",
    ),
    path(
        "autocomplete/account_new",
        autocomplete.account_create,
        name="kfet.account.create.autocomplete",
    ),
    # Account - Search
    path(
        "autocomplete/account_search",
        autocomplete.account_search,
        name="kfet.account.search.autocomplete",
    ),
    # Account - Read
    path(
        "accounts/<trigramme:trigramme>", views.account_read, name="kfet.account.read"
    ),
    # Account - Update
    path(
        "accounts/<trigramme:trigramme>/edit",
        views.account_update,
        name="kfet.account.update",
    ),
    # Account - Delete
    path(
        "accounts/<trigramme:trigramme>/delete",
        views.AccountDelete.as_view(),
        name="kfet.account.delete",
    ),
    # Account - Groups
    path("accounts/groups", views.account_group, name="kfet.account.group"),
    path(
        "accounts/groups/new",
        permission_required("kfet.manage_perms")(views.AccountGroupCreate.as_view()),
        name="kfet.account.group.create",
    ),
    path(
        "accounts/groups/<int:pk>/edit",
        permission_required("kfet.manage_perms")(views.AccountGroupUpdate.as_view()),
        name="kfet.account.group.update",
    ),
    path(
        "accounts/negatives",
        permission_required("kfet.view_negs")(views.AccountNegativeList.as_view()),
        name="kfet.account.negative",
    ),
    # Account - Statistics
    path(
        "accounts/<trigramme:trigramme>/stat/operations/list",
        views.AccountStatOperationList.as_view(),
        name="kfet.account.stat.operation.list",
    ),
    path(
        "accounts/<trigramme:trigramme>/stat/operations",
        views.AccountStatOperation.as_view(),
        name="kfet.account.stat.operation",
    ),
    path(
        "accounts/<trigramme:trigramme>/stat/balance/list",
        views.AccountStatBalanceList.as_view(),
        name="kfet.account.stat.balance.list",
    ),
    path(
        "accounts/<trigramme:trigramme>/stat/balance",
        views.AccountStatBalance.as_view(),
        name="kfet.account.stat.balance",
    ),
    # -----
    # Checkout urls
    # -----
    # Checkout - General
    path(
        "checkouts/",
        teamkfet_required(views.CheckoutList.as_view()),
        name="kfet.checkout",
    ),
    # Checkout - Create
    path(
        "checkouts/new",
        teamkfet_required(views.CheckoutCreate.as_view()),
        name="kfet.checkout.create",
    ),
    # Checkout - Read
    path(
        "checkouts/<int:pk>",
        teamkfet_required(views.CheckoutRead.as_view()),
        name="kfet.checkout.read",
    ),
    # Checkout - Update
    path(
        "checkouts/<int:pk>/edit",
        teamkfet_required(views.CheckoutUpdate.as_view()),
        name="kfet.checkout.update",
    ),
    # -----
    # Checkout Statement urls
    # -----
    # Checkout Statement - General
    path(
        "checkouts/statements/",
        teamkfet_required(views.CheckoutStatementList.as_view()),
        name="kfet.checkoutstatement",
    ),
    # Checkout Statement - Create
    path(
        "checkouts/<int:pk_checkout>/statements/add",
        teamkfet_required(views.CheckoutStatementCreate.as_view()),
        name="kfet.checkoutstatement.create",
    ),
    # Checkout Statement - Update
    path(
        "checkouts/<int:pk_checkout>/statements/<int:pk>/edit",
        teamkfet_required(views.CheckoutStatementUpdate.as_view()),
        name="kfet.checkoutstatement.update",
    ),
    # -----
    # Article urls
    # -----
    # Category - General
    path(
        "categories/",
        teamkfet_required(views.CategoryList.as_view()),
        name="kfet.category",
    ),
    # Category - Update
    path(
        "categories/<int:pk>/edit",
        teamkfet_required(views.CategoryUpdate.as_view()),
        name="kfet.category.update",
    ),
    # Article - General
    path(
        "articles/", teamkfet_required(views.ArticleList.as_view()), name="kfet.article"
    ),
    # Article - Create
    path(
        "articles/new",
        teamkfet_required(views.ArticleCreate.as_view()),
        name="kfet.article.create",
    ),
    # Article - Read
    path(
        "articles/<int:pk>",
        teamkfet_required(views.ArticleRead.as_view()),
        name="kfet.article.read",
    ),
    # Article - Update
    path(
        "articles/<int:pk>/edit",
        teamkfet_required(views.ArticleUpdate.as_view()),
        name="kfet.article.update",
    ),
    # Article - Delete
    path(
        "articles/<int:pk>/delete",
        views.ArticleDelete.as_view(),
        name="kfet.article.delete",
    ),
    # Article - Statistics
    path(
        "articles/<int:pk>/stat/sales/list",
        views.ArticleStatSalesList.as_view(),
        name="kfet.article.stat.sales.list",
    ),
    path(
        "articles/<int:pk>/stat/sales",
        views.ArticleStatSales.as_view(),
        name="kfet.article.stat.sales",
    ),
    # -----
    # K-Psul urls
    # -----
    path("k-psul/", views.kpsul, name="kfet.kpsul"),
    path(
        "k-psul/checkout_data",
        views.kpsul_checkout_data,
        name="kfet.kpsul.checkout_data",
    ),
    path(
        "k-psul/perform_operations",
        views.kpsul_perform_operations,
        name="kfet.kpsul.perform_operations",
    ),
    path(
        "k-psul/cancel_operations",
        views.kpsul_cancel_operations,
        name="kfet.kpsul.cancel_operations",
    ),
    path(
        "k-psul/articles_data",
        views.kpsul_articles_data,
        name="kfet.kpsul.articles_data",
    ),
    path(
        "k-psul/update_addcost",
        views.kpsul_update_addcost,
        name="kfet.kpsul.update_addcost",
    ),
    path(
        "k-psul/get_settings", views.kpsul_get_settings, name="kfet.kpsul.get_settings"
    ),
    # -----
    # JSON urls
    # -----
    path("history.json", views.history_json, name="kfet.history.json"),
    path(
        "accounts/<trigramme:trigramme>/.json",
        views.account_read_json,
        name="kfet.account.read.json",
    ),
    # -----
    # Settings urls
    # -----
    path("settings/", views.config_list, name="kfet.settings"),
    path("settings/edit", views.config_update, name="kfet.settings.update"),
    # -----
    # Transfers urls
    # -----
    path("transfers/", views.transfers, name="kfet.transfers"),
    path("transfers/new", views.transfers_create, name="kfet.transfers.create"),
    path("transfers/perform", views.perform_transfers, name="kfet.transfers.perform"),
    path("transfers/cancel", views.cancel_transfers, name="kfet.transfers.cancel"),
    # -----
    # Inventories urls
    # -----
    path(
        "inventaires/",
        teamkfet_required(views.InventoryList.as_view()),
        name="kfet.inventory",
    ),
    path("inventaires/new", views.inventory_create, name="kfet.inventory.create"),
    path(
        "inventaires/<int:pk>",
        teamkfet_required(views.InventoryRead.as_view()),
        name="kfet.inventory.read",
    ),
    # -----
    # Order urls
    # -----
    path("orders/", teamkfet_required(views.OrderList.as_view()), name="kfet.order"),
    path(
        "orders/<int:pk>",
        teamkfet_required(views.OrderRead.as_view()),
        name="kfet.order.read",
    ),
    path(
        "orders/suppliers/<int:pk>/edit",
        teamkfet_required(views.SupplierUpdate.as_view()),
        name="kfet.order.supplier.update",
    ),
    path(
        "orders/suppliers/<int:pk>/new-order", views.order_create, name="kfet.order.new"
    ),
    path(
        "orders/<int:pk>/to_inventory",
        views.order_to_inventory,
        name="kfet.order.to_inventory",
    ),
]

urlpatterns += [
    # K-Fêt Open urls
    path("open/", include("kfet.open.urls"))
]

clubs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class Club(models.Model):
    name = models.CharField(_("nom du club"), max_length=1000, unique=True)
    description = models.TextField(_("description"), blank=True)
    respos = models.ManyToManyField(
        User, verbose_name=_("responsables du club"), blank=True
    )

    def __str__(self):
        return self.name

kfet/cms/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from wagtail.admin.edit_handlers import (
    FieldPanel,
    FieldRowPanel,
    MultiFieldPanel,
    StreamFieldPanel,
)
from wagtail.core import blocks
from wagtail.core.fields import StreamField
from wagtail.core.models import Page
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.blocks import SnippetChooserBlock
from wagtail.snippets.models import register_snippet

from kfet.cms.context_processors import get_articles


@register_snippet
class MemberTeam(models.Model):
    first_name = models.CharField(
        verbose_name=_("Prénom"), blank=True, default="", max_length=255
    )
    last_name = models.CharField(
        verbose_name=_("Nom"), blank=True, default="", max_length=255
    )
    nick_name = models.CharField(
        verbose_name=_("Alias"), blank=True, default="", max_length=255
    )
    photo = models.ForeignKey(
        "wagtailimages.Image",
        verbose_name=_("Photo"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )

    class Meta:
        verbose_name = _("K-Fêt-eux-se")

    panels = [
        FieldPanel("first_name"),
        FieldPanel("last_name"),
        FieldPanel("nick_name"),
        ImageChooserPanel("photo"),
    ]

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name).strip()


class MenuBlock(blocks.StaticBlock):
    class Meta:
        icon = "list-ul"
        label = _("Carte")
        template = "kfetcms/block_menu.html"

    def get_context(self, *args, **kwargs):
        context = super().get_context(*args, **kwargs)
        context.update(get_articles())
        return context


class GroupTeamBlock(blocks.StructBlock):
    show_only = blocks.IntegerBlock(
        label=_("Montrer seulement"),
        required=False,
        help_text=_(
            "Nombre initial de membres affichés. Laisser vide pour tou-te-s "
            "les afficher."
        ),
    )
    members = blocks.ListBlock(
        SnippetChooserBlock(MemberTeam),
        label=_("K-Fêt-eux-ses"),
        classname="team-group",
    )

    class Meta:
        icon = "group"
        label = _("Groupe de K-Fêt-eux-ses")
        template = "kfetcms/block_teamgroup.html"


class ChoicesStreamBlock(blocks.StreamBlock):
    rich = blocks.RichTextBlock(label=_("Éditeur"))
    carte = MenuBlock()
    group_team = GroupTeamBlock()


class KFetStreamBlock(ChoicesStreamBlock):
    group = ChoicesStreamBlock(label=_("Contenu groupé"))


class KFetPage(Page):

    content = StreamField(KFetStreamBlock, verbose_name=_("Contenu"))

    # Layout fields

    TEMPLATE_COL_1 = "kfet/base_col_1.html"
    TEMPLATE_COL_2 = "kfet/base_col_2.html"
    TEMPLATE_COL_MULT = "kfet/base_col_mult.html"

    no_header = models.BooleanField(
        verbose_name=_("Sans en-tête"),
        default=False,
        help_text=_("Coché, l'en-tête (avec le titre) de la page n'est pas affiché."),
    )
    layout = models.CharField(
        verbose_name=_("Template"),
        choices=[
            (TEMPLATE_COL_1, _("Une colonne : centrée sur la page")),
            (TEMPLATE_COL_2, _("Deux colonnes : fixe à gauche, contenu à droite")),
            (TEMPLATE_COL_MULT, _("Contenu scindé sur plusieurs colonnes")),
        ],
        default=TEMPLATE_COL_MULT,
        max_length=255,
        help_text=_("Comment cette page devrait être affichée ?"),
    )
    main_size = models.CharField(
        verbose_name=_("Taille de la colonne de contenu"), blank=True, max_length=255
    )
    col_count = models.CharField(
        verbose_name=_("Nombre de colonnes"),
        blank=True,
        max_length=255,
        help_text=_(
            "S'applique au page dont le contenu est scindé sur plusieurs colonnes."
        ),
    )

    # Panels

    content_panels = Page.content_panels + [StreamFieldPanel("content")]

    layout_panel = [
        FieldPanel("no_header"),
        FieldPanel("layout"),
        FieldRowPanel([FieldPanel("main_size"), FieldPanel("col_count")]),
    ]

    settings_panels = [
        MultiFieldPanel(layout_panel, _("Affichage"))
    ] + Page.settings_panels

    # Base template
    template = "kfetcms/base.html"

    class Meta:
        verbose_name = _("page K-Fêt")
        verbose_name_plural = _("pages K-Fêt")

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)

        page = context["page"]

        if not page.seo_title:
            page.seo_title = page.title

        return context

kfet/open/views.py
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .open import kfet_open

TRUE_STR = ["1", "True", "true"]


@csrf_exempt
@require_POST
def raw_open(request):
    token = request.POST.get("token")
    if token != settings.KFETOPEN_TOKEN:
        raise PermissionDenied
    raw_open = request.POST.get("raw_open") in TRUE_STR
    kfet_open.raw_open = raw_open
    kfet_open.send_ws()
    return HttpResponse()


@permission_required("kfet.can_force_close", raise_exception=True)
@require_POST
def force_close(request):
    force_close = request.POST.get("force_close") in TRUE_STR
    kfet_open.force_close = force_close
    kfet_open.send_ws()
    return HttpResponse()

kfet/templates/kfet/account_group_form.html
{% extends 'kfet/base_form.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Permissions - Édition{% endblock %}
{% block header-title %}Modification des permissions{% endblock %}

{% block main %}

<form action="" method="post" class="form-horizontal">
  {% csrf_token %}
  <div class="form-group">
    <label for="{{ form.name.id_for_label }}" class="col-sm-2 control-label">{{ form.name.label }}</label>
    <div class="col-sm-10">
      <div class="input-group">
        <span class="input-group-addon">K-Fêt</span>
        {{ form.name|add_class:"form-control" }}
      </div>
      {% if form.name.errors %}
        <span class="help-block">{{ form.name.errors }}</span>
      {% endif %}
      {% if form.name.help_text %}
        <span class="help-block">{{ form.name.help_text }}</span>
      {% endif %}
    </div>
  </div>
  {% include "kfet/form_field_snippet.html" with field=form.permissions %}
  {% include "kfet/form_submit_snippet.html" with value="Enregistrer" %}
</form>

<script type="text/javascript">
$(document).ready(function() {
    let $name_input = $("#id_name");
    let raw_name = $name_input.val();
    let prefix = "K-Fêt ";
    if (raw_name.startsWith(prefix))
        $name_input.val(raw_name.substring(prefix.length));
});
</script>

{% endblock %}

kfet/templates/kfet/article.html
{% extends 'kfet/base_col_2.html' %}

{% block title %}Articles{% endblock %}
{% block header-title %}Articles{% endblock %}

{% block fixed %}

<aside>
  <div class="heading">
    {{ nb_articles }}
    <span class="sub">article{{ nb_articles|pluralize }}</span>
  </div>
  <div class="heading">
    <span class="sub">dont {{ articles|length }} en vente</span>
  </div>
</aside>

<div class="buttons">
  <a class="btn btn-primary" href="{% url 'kfet.article.create' %}">
    <span class="glyphicon glyphicon-plus"></span>
    <span>Nouvel article</span>
  </a>
  <a class="btn btn-primary" href="{% url 'kfet.category' %}">
    Catégories
  </a>
</div>

{% endblock %}

{% block main %}
<h2>Article{{ articles|length|pluralize}} en vente</h2>
<div class="table-responsive">
  <table
      class="table table-hover table-condensed sortable"
      {# Initial sort: [(is_sold,desc), (name,asc)] #}
      data-sortlist="[[3,1], [0,0]]">
    <thead>
      <tr>
        <td>Nom</td>
        <td class="text-right">Prix</td>
        <td class="text-right">Stock</td>
        <td class="text-right" data-sorter="article__is_sold">En vente</td>
        <td class="text-right" data-sorter="article__hidden">Affiché</td>
        <td class="text-right" data-sorter="shortDate">Dernier inventaire</td>
      </tr>
    </thead>
    {% regroup articles by category as category_list %}

    {% for category in category_list %}
      <tbody class="tablesorter-no-sort">
        <tr class="section">
          <td colspan="6">{{ category.grouper }}</td>
        </tr>
      </tbody>
      <tbody>
        {% for article in category.list %}
          <tr>
            <td>
              <a href="{% url 'kfet.article.read' article.pk %}">
                {{ article.name }}
              </a>
            </td>
            <td class="text-right">{{ article.price }}€</td>
            <td class="text-right">{{ article.stock }}</td>
            <td class="text-right">{{ article.is_sold | yesno:"En vente,Non vendu"}}</td>
            <td class="text-right">{{ article.hidden | yesno:"Caché,Affiché" }}</td>
            {% with last_inventory=article.inventory.0 %}
            <td class="text-right" title="{{ last_inventory.at }}">
              {{ last_inventory.at|date:'d/m/Y H:i' }}
            </td>
            {% endwith %}
          </tr>
        {% endfor %}
      </tbody>
    {% endfor %}
  </table>
</div>

<h2>Article{{ not_sold_articles|length|pluralize }} non vendu{{ nots_sold_article|length|pluralize }}</h2>
<div class="table-responsive">
  <table
      class="table table-hover table-condensed sortable"
      {# Initial sort: [(is_sold,desc), (name,asc)] #}
      data-sortlist="[[3,1], [0,0]]">
    <thead>
      <tr>
        <td>Nom</td>
        <td class="text-right">Prix</td>
        <td class="text-right">Stock</td>
        <td class="text-right" data-sorter="article__is_sold">En vente</td>
        <td class="text-right" data-sorter="article__hidden">Affiché</td>
        <td class="text-right" data-sorter="shortDate">Dernier inventaire</td>
      </tr>
    </thead>
    {% regroup not_sold_articles by category as not_sold_category_list %}

    {% for category in not_sold_category_list %}
      <tbody class="tablesorter-no-sort">
        <tr class="section">
          <td colspan="6">{{ category.grouper }}</td>
        </tr>
      </tbody>
      <tbody>
        {% for article in category.list %}
          <tr>
            <td>
              <a href="{% url 'kfet.article.read' article.pk %}">
                {{ article.name }}
              </a>
            </td>
            <td class="text-right">{{ article.price }}€</td>
            <td class="text-right">{{ article.stock }}</td>
            <td class="text-right">{{ article.is_sold | yesno:"En vente,Non vendu"}}</td>
            <td class="text-right">{{ article.hidden | yesno:"Caché,Affiché" }}</td>
            {% with last_inventory=article.inventory.0 %}
            <td class="text-right" title="{{ last_inventory.at }}">
              {{ last_inventory.at|date:'d/m/Y H:i' }}
            </td>
            {% endwith %}
          </tr>
        {% endfor %}
      </tbody>
    {% endfor %}
  </table>
</div>
</div>

{% endblock %}

kfet/templates/kfet/article_create.html
{% extends 'kfet/base_form.html' %}

{% block title %}Nouvel article{% endblock %}
{% block header-title %}Création d'un article{% endblock %}

{% block main %}

{% include "kfet/form_full_snippet.html" with authz=perms.kfet.add_article submit_text="Enregistrer" %}

{% endblock %}

kfet/templates/kfet/article_suppliers_snippet.html
<table
    class="table table-hover table-condensed sortable"
    {# Initial sort: [(at,desc)] #}
    data-sortlist="[[0,1]]">
  <thead>
    <tr>
      <td data-sorter="shortDate">Date</td>
      <td>Fournisseur</td>
      <td>HT</td>
      <td>TVA</td>
      <td>Droits</td>
    </tr>
  </thead>
  <tbody>
    {% for supplierart in supplierarts %}
    <tr>
      <td title="{{ supplierart.at }}">
        {{ supplierart.at|date:'d/m/Y' }}
      </td>
      <td>{{ supplierart.supplier.name }}</td>
      <td>{{ supplierart.price_HT|default_if_none:"" }}</td>
      <td>{{ supplierart.TVA|default_if_none:"" }}</td>
      <td>{{ supplierart.rights|default_if_none:"" }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

kfet/templates/kfet/base_col_2.html
{% extends "kfet/base.html" %}

{% block content %}

<div class="row content-row">
  <div class="fixed-col {% block fixed-size %}col-sm-3{% endblock %}">
    <div class="fixed {% block fixed-class %}{% endblock %}">
      {% block fixed %}{% endblock %}
    </div>
  </div>
  <div class="main-col {% block main-size %}col-sm-9{% endblock %}">
    {% include "kfet/base_messages.html" %}
    <div class="main {% block main-class %}{% endblock %}">
      {% block main %}{% endblock %}
    </div>
  </div>
</div>

{% endblock %}

kfet/templates/kfet/base_col_mult.html
{% extends "kfet/base.html" %}

{% block header-class %}text-center{% endblock %}

{% block content %}

<div class="row content-row">
  <div class="main-col {% block main-size %}col-xs-12{% endblock %}">
    {% include "kfet/base_messages.html" %}
    <div class="main {% block main-class %}{% endblock %}">
      <div class="main-col-mult {% block mult-count %}column-md-2{% endblock %}">
        {% block main %}{% endblock %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

kfet/templates/kfet/category.html
{% extends "kfet/base_col_2.html" %}

{% block title %}Categories d'articles{% endblock %}
{% block header-title %}Categories d'articles{% endblock %}

{% block fixed %}

<aside>
  <div class="heading">
    {{ categories|length }}
    <span class="sub">catégorie{{ categories|length|pluralize }}</span>
  </div>
</aside>

{% endblock %}

{% block main %}

<div class="table-responsive">
  <table
      class="table table-hover table-condensed sortable"
      {# Initial sort: [(name,asc)] #}
      data-sortlist="[[0,0]]">
    <thead>
      <tr>
        <td>Nom</td>
        <td class="text-right">Nombre d'articles</td>
        <td class="text-right" data-sorter="yesno">Peut être majorée</td>
        <td class="text-right" data-sorter="yesno">Réduction COF appliquée</td>
      </tr>
    </thead>
    <tbody>
      {% for category in categories %}
      <tr>
        <td>
          <a href="{% url 'kfet.category.update' category.pk %}">
            {{ category.name }}
          </a>
        </td>
        <td class="text-right">{{ category.articles.all|length }}</td>
        <td class="text-right">{{ category.has_addcost | yesno:"Oui,Non"}}</td>
        <td class="text-right">{{ category.has_reduction | yesno:"Oui,Non"}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

kfet/templates/kfet/form_submit_snippet.html
<div class="form-group">
  <div class="col-sm-6 col-sm-offset-3 text-center">
    <input type="submit" value="{{ value }}" class="btn btn-primary btn-lg">
  </div>
</div>

kfet/templates/kfet/settings_update.html
{% extends "kfet/base_form.html" %}

{% block title %}Modification des paramètres{% endblock %}
{% block header-title %}Modification des paramètres{% endblock %}

{% block main %}

{% include "kfet/form_full_snippet.html" with authz=perms.kfet.change_settings submit_text="Mettre à jour"%}

{% endblock %}